- name: Test Execution Environment and Credentials
  hosts: localhost
  tasks:
    - name: Get Cluster Version
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: ClusterVersion
        name: version
      register: cluster_version

    - name: Debug Version
      ansible.builtin.debug:
        var: cluster_version
